name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 7,8,9,10,11 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "sunibamidoan6@gmail.com"
          git config --local user.name "suni"
          git add -A
          
          arr[0]="Reparo"
          arr[1]="Riddikulus"
          arr[2]="Accio"
          arr[3]="Alohomora"
          arr[4]="Crucio"
          arr[5]="Petrificus Totalus"
          arr[6]="Wingardium Leviosa"
          arr[7]="Sectumsempra"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}